server.port=8080

# Base de données H2 en mémoire
spring.datasource.url=jdbc:h2:mem:formationsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Exécution automatique du script de données
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always